// Mock data for the Client Finder platform
// Realistic businesses across multiple countries and industries

export const MOCK_BUSINESSES = [
  {
    id: 'biz-001',
    name: 'The Grand Sapphire Hotel',
    industry: 'hotel',
    icon: '🏨',
    rating: 3.8,
    reviews: 234,
    address: '42 Park Lane, Mayfair, London W1K 1BE',
    city: 'London',
    country: 'UK',
    lat: 51.5074,
    lng: -0.1528,
    phone: '+44 20 7629 8888',
    website: 'www.grandsapphire.co.uk',
    hasWebsite: true,
    employees: '50-100',
    revenue: '$2M-5M',
    founded: 2012,
    status: 'discovered',
    digitalScore: 42,
    techStack: ['WordPress', 'jQuery'],
    missingTech: ['Analytics', 'Booking Engine', 'CRM', 'Email Marketing'],
    socialPresence: { google: true, instagram: false, facebook: true, linkedin: false, twitter: false },
  },
  {
    id: 'biz-002',
    name: 'Mumbai Spice Garden',
    industry: 'restaurant',
    icon: '🍽️',
    rating: 4.2,
    reviews: 567,
    address: 'Linking Road, Bandra West, Mumbai 400050',
    city: 'Mumbai',
    country: 'India',
    lat: 19.0596,
    lng: 72.8295,
    phone: '+91 22 2640 9999',
    website: 'www.mumbaispicegarden.in',
    hasWebsite: true,
    employees: '20-50',
    revenue: '$500K-1M',
    founded: 2015,
    status: 'discovered',
    digitalScore: 35,
    techStack: ['Wix'],
    missingTech: ['Online Ordering', 'SEO', 'Mobile App', 'Google Ads'],
    socialPresence: { google: true, instagram: true, facebook: true, linkedin: false, twitter: false },
  },
  {
    id: 'biz-003',
    name: 'TechVault Solutions',
    industry: 'saas',
    icon: '💻',
    rating: 4.5,
    reviews: 89,
    address: '350 5th Avenue, Suite 4800, New York, NY 10118',
    city: 'New York',
    country: 'USA',
    lat: 40.7484,
    lng: -73.9857,
    phone: '+1 212-555-0142',
    website: 'www.techvault.io',
    hasWebsite: true,
    employees: '10-20',
    revenue: '$1M-2M',
    founded: 2019,
    status: 'analyzed',
    digitalScore: 68,
    techStack: ['React', 'Node.js', 'AWS', 'Stripe'],
    missingTech: ['Content Marketing', 'SEO Blog', 'Chatbot'],
    socialPresence: { google: true, instagram: false, facebook: false, linkedin: true, twitter: true },
  },
  {
    id: 'biz-004',
    name: 'Desert Rose Wellness Spa',
    industry: 'beauty',
    icon: '💇',
    rating: 4.7,
    reviews: 312,
    address: 'Dubai Mall, Financial Center Rd, Dubai',
    city: 'Dubai',
    country: 'UAE',
    lat: 25.1972,
    lng: 55.2744,
    phone: '+971 4 555 6789',
    website: '',
    hasWebsite: false,
    employees: '10-20',
    revenue: '$1M-2M',
    founded: 2018,
    status: 'discovered',
    digitalScore: 18,
    techStack: [],
    missingTech: ['Website', 'Booking System', 'Google My Business', 'Instagram Strategy', 'CRM'],
    socialPresence: { google: true, instagram: true, facebook: false, linkedin: false, twitter: false },
  },
  {
    id: 'biz-005',
    name: 'Singapore Fitness Hub',
    industry: 'fitness',
    icon: '💪',
    rating: 4.1,
    reviews: 189,
    address: '1 Raffles Place, #08-01, Singapore 048616',
    city: 'Singapore',
    country: 'Singapore',
    lat: 1.2840,
    lng: 103.8510,
    phone: '+65 6555 4321',
    website: 'www.sgfithub.com',
    hasWebsite: true,
    employees: '20-50',
    revenue: '$500K-1M',
    founded: 2017,
    status: 'contacted',
    digitalScore: 52,
    techStack: ['Squarespace', 'MindBody'],
    missingTech: ['Mobile App', 'Nutrition Platform', 'AI Coaching', 'Video Content'],
    socialPresence: { google: true, instagram: true, facebook: true, linkedin: false, twitter: false },
  },
  {
    id: 'biz-006',
    name: 'Sakura Ryokan',
    industry: 'hotel',
    icon: '🏨',
    rating: 4.8,
    reviews: 421,
    address: 'Higashiyama-ku, Kyoto, Japan',
    city: 'Tokyo',
    country: 'Japan',
    lat: 35.0032,
    lng: 135.7756,
    phone: '+81 75-561-0001',
    website: 'www.sakuraryokan.jp',
    hasWebsite: true,
    employees: '20-50',
    revenue: '$2M-5M',
    founded: 1998,
    status: 'discovered',
    digitalScore: 38,
    techStack: ['HTML/CSS', 'PHP'],
    missingTech: ['Modern Website', 'OTA Integration', 'Multi-language', 'Reviews Management'],
    socialPresence: { google: true, instagram: false, facebook: false, linkedin: false, twitter: true },
  },
  {
    id: 'biz-007',
    name: 'AutoKraft Premium',
    industry: 'automotive',
    icon: '🚗',
    rating: 3.9,
    reviews: 156,
    address: '15 Alexanderplatz, Berlin 10178',
    city: 'Berlin',
    country: 'Germany',
    lat: 52.5219,
    lng: 13.4132,
    phone: '+49 30 2456 7890',
    website: 'www.autokraft-berlin.de',
    hasWebsite: true,
    employees: '10-20',
    revenue: '$1M-2M',
    founded: 2014,
    status: 'discovered',
    digitalScore: 44,
    techStack: ['WordPress', 'WooCommerce'],
    missingTech: ['Lead Capture', 'CRM', 'Test Drive Booking', 'Video Showroom'],
    socialPresence: { google: true, instagram: false, facebook: true, linkedin: false, twitter: false },
  },
  {
    id: 'biz-008',
    name: 'EduLearn Academy',
    industry: 'education',
    icon: '🎓',
    rating: 4.3,
    reviews: 278,
    address: '200 University Ave W, Toronto, ON M5H 3C6',
    city: 'Toronto',
    country: 'Canada',
    lat: 43.6510,
    lng: -79.3834,
    phone: '+1 416-555-0198',
    website: 'www.edulearnacademy.ca',
    hasWebsite: true,
    employees: '50-100',
    revenue: '$2M-5M',
    founded: 2010,
    status: 'replied',
    digitalScore: 55,
    techStack: ['Moodle', 'WordPress', 'Zoom'],
    missingTech: ['LMS Upgrade', 'Student Portal', 'Marketing Automation', 'AI Tutoring'],
    socialPresence: { google: true, instagram: true, facebook: true, linkedin: true, twitter: false },
  },
  {
    id: 'biz-009',
    name: 'Café Paulista',
    industry: 'restaurant',
    icon: '🍽️',
    rating: 4.6,
    reviews: 892,
    address: 'Rua Augusta 1508, São Paulo, SP 01304-001',
    city: 'São Paulo',
    country: 'Brazil',
    lat: -23.5613,
    lng: -46.6569,
    phone: '+55 11 3456-7890',
    website: '',
    hasWebsite: false,
    employees: '10-20',
    revenue: '$200K-500K',
    founded: 2016,
    status: 'discovered',
    digitalScore: 22,
    techStack: [],
    missingTech: ['Website', 'Online Menu', 'Delivery Integration', 'Google Maps', 'Social Media'],
    socialPresence: { google: true, instagram: true, facebook: false, linkedin: false, twitter: false },
  },
  {
    id: 'biz-010',
    name: 'LegalEdge Advisors',
    industry: 'legal',
    icon: '⚖️',
    rating: 4.4,
    reviews: 67,
    address: '283 George St, Sydney NSW 2000',
    city: 'Sydney',
    country: 'Australia',
    lat: -33.8677,
    lng: 151.2072,
    phone: '+61 2 9555 4321',
    website: 'www.legaledge.com.au',
    hasWebsite: true,
    employees: '20-50',
    revenue: '$5M-10M',
    founded: 2008,
    status: 'meeting',
    digitalScore: 48,
    techStack: ['WordPress', 'Clio'],
    missingTech: ['Client Portal', 'Document Automation', 'SEO', 'Content Marketing'],
    socialPresence: { google: true, instagram: false, facebook: true, linkedin: true, twitter: false },
  },
  {
    id: 'biz-011',
    name: 'Spice Route Kitchen',
    industry: 'restaurant',
    icon: '🍽️',
    rating: 4.0,
    reviews: 342,
    address: 'Jubilee Hills, Hyderabad 500033',
    city: 'Hyderabad',
    country: 'India',
    lat: 17.4310,
    lng: 78.4070,
    phone: '+91 40 2355 6789',
    website: 'www.spiceroutekitchen.in',
    hasWebsite: true,
    employees: '20-50',
    revenue: '$200K-500K',
    founded: 2019,
    status: 'discovered',
    digitalScore: 30,
    techStack: ['WordPress'],
    missingTech: ['Online Ordering', 'Mobile App', 'Loyalty Program', 'SEO'],
    socialPresence: { google: true, instagram: true, facebook: true, linkedin: false, twitter: false },
  },
  {
    id: 'biz-012',
    name: 'CloudSync Dynamics',
    industry: 'saas',
    icon: '💻',
    rating: 4.2,
    reviews: 45,
    address: 'HITEC City, Madhapur, Hyderabad 500081',
    city: 'Hyderabad',
    country: 'India',
    lat: 17.4474,
    lng: 78.3762,
    phone: '+91 40 6789 0123',
    website: 'www.cloudsyncdynamics.com',
    hasWebsite: true,
    employees: '50-100',
    revenue: '$2M-5M',
    founded: 2020,
    status: 'converted',
    digitalScore: 71,
    techStack: ['React', 'Django', 'AWS', 'PostgreSQL'],
    missingTech: ['Content Marketing', 'Webinar Platform', 'Customer Portal'],
    socialPresence: { google: true, instagram: false, facebook: false, linkedin: true, twitter: true },
  },
];

export const MOCK_ANALYSIS = {
  'biz-001': {
    websiteAudit: {
      overall: 42,
      mobile: 35,
      speed: 48,
      seo: 38,
      accessibility: 52,
      issues: [
        { type: 'critical', text: 'No mobile responsive design — 62% of hotel searches are mobile' },
        { type: 'critical', text: 'Page load time 8.2s — industry average is 2.5s' },
        { type: 'high', text: 'No booking engine — redirects to third-party OTA' },
        { type: 'high', text: 'Missing schema markup for hotel rich snippets' },
        { type: 'medium', text: 'No SSL certificate — browser shows "Not Secure"' },
        { type: 'low', text: 'Outdated jQuery version with known vulnerabilities' },
      ],
    },
    gaps: [
      {
        id: 'gap-1',
        title: 'No Direct Booking System',
        severity: 'critical',
        description: 'The hotel relies 100% on OTAs (Booking.com, Expedia) which charge 15-25% commission per booking. A direct booking engine would save £180K-£450K annually based on their room volume.',
        evidence: 'Website has no booking functionality. All CTAs redirect to Booking.com.',
        opportunity: 'Build a direct booking engine → save 15-25% on OTA commissions → estimated £180K-450K/year savings',
        pitchAngle: 'I noticed your guests have to leave your website to book a room. Every booking through Booking.com costs you 15-25% in commission. What if we could capture those bookings directly?',
      },
      {
        id: 'gap-2',
        title: 'Mobile Experience is Broken',
        severity: 'critical',
        description: '62% of hotel searches happen on mobile devices, but the site is not responsive. Text overlaps, images are cut, and navigation is unusable on phones.',
        evidence: 'Google Mobile-Friendly Test: FAIL. Lighthouse mobile score: 35/100.',
        opportunity: 'Mobile-responsive redesign → capture the 62% of mobile searchers currently bouncing',
        pitchAngle: 'I tested your website on my phone and the experience was quite frustrating. With 62% of your potential guests searching on mobile, this is likely costing you significant bookings.',
      },
      {
        id: 'gap-3',
        title: 'No Review Management Strategy',
        severity: 'high',
        description: 'The hotel has a 3.8 rating with several recent negative reviews left unanswered. Competitors in the area average 4.3+ stars.',
        evidence: '12 of the last 20 reviews are 3 stars or below. Zero management responses in 6 months.',
        opportunity: 'Implement review response system + quality improvements → target 4.3+ rating within 6 months',
        pitchAngle: 'I noticed some recent reviews mention specific issues that haven\'t been addressed. Hotels that respond to reviews within 24 hours see a 0.5 star improvement on average.',
      },
      {
        id: 'gap-4',
        title: 'Zero Email Marketing',
        severity: 'medium',
        description: 'No newsletter, no post-stay follow-up, no repeat guest campaigns. The hotel captures zero guest data for remarketing.',
        evidence: 'No email signup forms on website. No observable email marketing campaigns.',
        opportunity: 'Email marketing for hotels drives 40:1 ROI. Even a basic post-stay campaign could drive 15-20% repeat bookings.',
        pitchAngle: 'Are you currently staying in touch with past guests? Hotels that send just one post-stay email see a 15-20% increase in repeat bookings.',
      },
    ],
    competitors: [
      { name: 'The Claridge London', score: 78, rating: 4.6, reviews: 1240 },
      { name: 'Park Lane Suites', score: 65, rating: 4.2, reviews: 890 },
      { name: 'Mayfair Crown Hotel', score: 58, rating: 4.0, reviews: 456 },
    ],
  },
};

export const MOCK_MESSAGES = {
  'biz-001': {
    professional: {
      subject: 'Quick question about your hotel\'s online booking experience',
      body: `Hi there,

I was researching luxury hotels in Mayfair and came across The Grand Sapphire. Your property looks stunning, and I noticed you've built a solid reputation with 234 reviews.

However, I spotted something that might be quietly costing you a significant amount — your guests currently have to leave your website to book through Booking.com. At their standard 15-25% commission rate, that could mean £180K-£450K leaving your business annually.

I work with boutique hotels to build direct booking systems that keep that revenue in-house. One of our clients, a 40-room hotel in Chelsea, saw their direct bookings increase by 340% within 4 months after we implemented their system.

Would you be open to a 15-minute call this week to explore if we could do something similar for The Grand Sapphire?

Best regards`,
    },
    casual: {
      subject: 'Noticed something about your hotel\'s bookings 👋',
      body: `Hey!

Love what you've done with The Grand Sapphire — the Mayfair location is incredible.

Quick observation though: I tried to book a room directly through your site and ended up on Booking.com. That's a 15-25% commission on every single booking! For a hotel your size, that could be hundreds of thousands in lost revenue each year.

We help hotels like yours build beautiful, direct booking systems that guests actually prefer — and it keeps all that commission money where it belongs (with you!).

Interested in a quick chat about it? No pressure at all.

Cheers!`,
    },
    consultative: {
      subject: 'Analysis: 3 revenue leaks I found on your hotel website',
      body: `Hi,

I recently conducted a digital audit of The Grand Sapphire Hotel as part of our hospitality research. I found three specific areas where you're likely losing significant revenue:

1. **No direct booking engine** — Every booking goes through OTAs at 15-25% commission (~£180K-£450K/year potential savings)
2. **Mobile experience** — Your site scores 35/100 on mobile, but 62% of hotel searches are on phones
3. **Review gap** — Your 3.8 rating is below the Mayfair average of 4.3, with 12 recent negative reviews unanswered

I've prepared a brief analysis doc with specific numbers and actionable recommendations — would you like me to send it over?

We've helped 15+ hotels in London address exactly these issues, typically seeing a 40-60% increase in direct revenue within 6 months.

Best regards`,
    },
  },
};

export const MOCK_PIPELINE = {
  discovered: ['biz-001', 'biz-002', 'biz-004', 'biz-006', 'biz-007', 'biz-009', 'biz-011'],
  analyzed: ['biz-003'],
  contacted: ['biz-005'],
  replied: ['biz-008'],
  meeting: ['biz-010'],
  converted: ['biz-012'],
};

export const MOCK_ANALYTICS = {
  totalScanned: 1247,
  totalAnalyzed: 389,
  totalContacted: 156,
  totalReplied: 67,
  totalMeetings: 28,
  totalConverted: 12,
  replyRate: 42.9,
  conversionRate: 7.7,
  avgDealValue: 8500,
  weeklyGrowth: {
    scanned: 12.4,
    analyzed: 8.2,
    contacted: 15.1,
    replied: -3.2,
    meetings: 22.5,
    converted: 50.0,
  },
  channelPerformance: [
    { channel: 'Email', sent: 98, replied: 38, meetings: 15, rate: 38.8 },
    { channel: 'LinkedIn', sent: 42, replied: 22, meetings: 10, rate: 52.4 },
    { channel: 'WhatsApp', sent: 16, replied: 7, meetings: 3, rate: 43.8 },
  ],
  topIndustries: [
    { industry: 'Hotels & Hospitality', contacted: 45, converted: 5, rate: 11.1 },
    { industry: 'Restaurants & Cafes', contacted: 38, converted: 3, rate: 7.9 },
    { industry: 'SaaS & Tech', contacted: 28, converted: 2, rate: 7.1 },
    { industry: 'Retail & Shopping', contacted: 22, converted: 1, rate: 4.5 },
    { industry: 'Healthcare', contacted: 23, converted: 1, rate: 4.3 },
  ],
  recentActivity: [
    { type: 'reply', business: 'EduLearn Academy', message: 'Interested, send me more details', time: '2 hours ago' },
    { type: 'meeting', business: 'LegalEdge Advisors', message: 'Meeting scheduled for Friday 3pm', time: '5 hours ago' },
    { type: 'sent', business: 'Singapore Fitness Hub', message: 'Follow-up email sent', time: '8 hours ago' },
    { type: 'scan', business: 'Berlin Region', message: '24 new businesses discovered', time: '12 hours ago' },
    { type: 'converted', business: 'CloudSync Dynamics', message: 'Contract signed — $12,000 deal', time: '1 day ago' },
    { type: 'reply', business: 'Sakura Ryokan', message: 'Not interested right now', time: '1 day ago' },
  ],
};
